- name: Deploy Hello World Module
  hosts: all
  vars:
    required_vars:
      - remote_image
    software_name: "hello-world"
    # Directories
    software_dir: "{{ base_dir }}/{{ software_name }}/{{ version }}"
    module_dir: "{{ base_dir }}/modulefiles/{{ software_name }}"
    # Paths
    software_path: "{{ software_dir }}/{{ software_name }}"
    module_path: "{{ module_dir }}/{{ version }}.lua"

  pre_tasks:
    - name: Ensure required variables are set
      assert:
        that: "{{ item }} is defined"
        fail_msg: "Missing required variable: {{ item }}. Pass it using -e '{{ item }}=value'"
      loop: "{{ required_vars }}"

  tasks:
    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ module_dir }}"
        - "{{ software_dir }}"

    - name: Load Singularity module and Pull image
      shell: |
        module load singularity/{{ singularity_version }}
        singularity pull -F {{ software_path }} {{ remote_image }}
      args:
        executable: /bin/bash

    - name: Create module file
      template:
        src: modulefile.lua.jinja2
        dest: "{{ module_path }}"
        mode: "0644"
