name: CI/CD Pipeline

on:
  release:
    types: [published]

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          python -m pip install build
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/supervisor_python-0.1.0-py3-none-any.whl

  deploy-staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-wheel

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PAWSEY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Deploy to Staging
        run: |
          ansible-playbook -i inventory.yml deploy.yml -l staging --extra-vars "version=${{ env.TAG }}"

  test:
    name: Test
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PAWSEY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Deploy to Staging
        run: |
          ansible-playbook -i inventory.yml test.yml --extra-vars "version=${{ env.TAG }}"

  verify_results:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: manual-approval
      # This enforces a manual approval step through GitHub's UI
      # You need to configure this environment in your repo settings
      # under Settings > Environments > New environment
      # and add required reviewers
    steps:
      - name: Echo verification
        run: echo "Manually check the test results"

  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-wheel

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PAWSEY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Deploy to Staging
        run: |
          ansible-playbook -i inventory.yml deploy.yml --extra-vars "version=${{ env.TAG }}"
