name: CI/CD Pipeline

on:
  release:
    types: [published]

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            VERSION=${{ env.TAG }}
          push: true
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/hello-world:${{ env.TAG }}
            ${{ vars.DOCKER_HUB_USERNAME }}/hello-world:latest

  deploy-staging:
    name: Deploy Staging
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PAWSEY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt -y install ansible

      - name: Deploy to Staging
        run: |
          ansible-playbook -i inventory.yml deploy.yml -l staging --extra-vars "version=${{ env.TAG }}"

  test:
    name: Test
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PAWSEY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt -y install ansible

      - name: Deploy to Staging
        run: |
          ansible-playbook -i inventory.yml test.yml --extra-vars "version=${{ env.TAG }}"

  verify-results:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: manual-approval
      # This enforces a manual approval step through GitHub's UI
      # You need to configure this environment in your repo settings
      # under Settings > Environments > New environment
      # and add required reviewers
    steps:
      - name: Echo verification
        run: echo "Manually check the test results"

  deploy-production:
    name: Deploy Production
    needs: verify-results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PAWSEY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt -y install ansible

      - name: Deploy to Staging
        run: |
          ansible-playbook -i inventory.yml deploy.yml --extra-vars "version=${{ env.TAG }}"
