name: Development CD Pipeline

on:
  workflow_dispatch:

env:
  REF_NAME: ${{ github.ref_name }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            VERSION=${{ env.REF_NAME }}
          push: true
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/hello-world:${{ env.REF_NAME }}

  deploy-development:
    name: Deploy Development
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PAWSEY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt -y install ansible

      - name: Deploy to Development
        run: |
          ansible-playbook deploy.yml -i inventory/dev.yml --extra-vars "version=${{ env.REF_NAME }}, ansible_user=ksmith1, remote_image=docker://${{ vars.DOCKER_HUB_USERNAME }}/hello-world:${{ env.REF_NAME }}"
